const { Resend } = require("resend");

const escapeHtml = (value) =>
  String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

const isValidEmail = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);

module.exports = async (req, res) => {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method Not Allowed" });
  }

  try {
    const { name, email, subject, message } = req.body || {};

    if (!name || !email || !subject || !message) {
      return res
        .status(400)
        .json({ error: "All required fields must be filled." });
    }

    if (
      name.length > 80 ||
      email.length > 120 ||
      subject.length > 120 ||
      message.length > 2000
    ) {
      return res.status(400).json({ error: "One or more fields are too long." });
    }

    if (!isValidEmail(email)) {
      return res.status(400).json({ error: "Please provide a valid email." });
    }

    if (!process.env.RESEND_KEY || !process.env.MAIL_TO) {
      return res.status(500).json({ error: "Email service is not configured." });
    }

    const safeName = escapeHtml(name);
    const safeEmail = escapeHtml(email);
    const safeSubject = escapeHtml(subject);
    const safeMessage = escapeHtml(message).replace(/\n/g, "<br />");

    const html = `
      <div style="background:#0f172a;padding:32px 12px;">
        <div style="max-width:640px;margin:0 auto;background:#ffffff;border-radius:18px;overflow:hidden;box-shadow:0 12px 30px rgba(15,23,42,0.25);font-family:Arial, sans-serif;">
          <div style="background:linear-gradient(90deg,#0ea5e9,#6366f1);padding:18px 24px;color:#ffffff;">
            <div style="font-size:12px;letter-spacing:1.6px;text-transform:uppercase;opacity:0.85;">Portfolio Contact</div>
            <div style="font-size:24px;font-weight:700;margin-top:6px;">New Message</div>
          </div>

          <div style="padding:24px;color:#0f172a;">
            <div style="margin-bottom:14px;color:#64748b;font-size:13px;">
              You received a new message from your portfolio contact form.
            </div>

            <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;margin-bottom:20px;">
              <tr>
                <td style="padding:8px 0;color:#475569;font-size:12px;width:120px;">Name</td>
                <td style="padding:8px 0;font-weight:600;">${safeName}</td>
              </tr>
              <tr>
                <td style="padding:8px 0;color:#475569;font-size:12px;">Email</td>
                <td style="padding:8px 0;font-weight:600;">${safeEmail}</td>
              </tr>
              <tr>
                <td style="padding:8px 0;color:#475569;font-size:12px;">Subject</td>
                <td style="padding:8px 0;font-weight:600;">${safeSubject}</td>
              </tr>
            </table>

            <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:16px;">
              <div style="font-size:13px;color:#64748b;text-transform:uppercase;letter-spacing:1px;margin-bottom:10px;">Message</div>
              <div style="font-size:15px;line-height:1.6;color:#0f172a;">${safeMessage}</div>
            </div>
          </div>

          <div style="padding:16px 24px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8;">
            This email was generated by your portfolio site contact form.
          </div>
        </div>
      </div>
    `;

    const resend = new Resend(process.env.RESEND_KEY);
    const fromAddress =
      process.env.MAIL_FROM || "Contact Form <onboarding@resend.dev>";

    const { data, error } = await resend.emails.send({
      from: fromAddress,
      to: process.env.MAIL_TO,
      replyTo: email,
      subject: `${subject} | Portfolio Contact`,
      html,
    });

    if (error) {
      console.error("Resend Error:", error);
      return res.status(500).json({
        error:
          error.message ||
          "Email could not be sent. Please try again later.",
      });
    }

    return res.status(200).json({ success: true, id: data?.id });
  } catch (error) {
    console.error("Email Error:", error);
    return res
      .status(500)
      .json({ error: "Something went wrong. Please try again later." });
  }
};
